version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - pwd
      - ls -l
      - echo $APP_CONFIG
      - sh script/cicd/setup_initial.sh $APP_CONFIG
      - sh script/pack_components.sh $APP_CONFIG
      - npm install

  build:
    commands:
      - echo ==--------ListStacks---------==
      - cdk list
      - echo ==--------StartDeploy---------==
      - cdk deploy *-ThingInstallerStack --require-approval never
      - cdk deploy *-ThingMonitorStack --require-approval never --outputs-file ./script/thing/install-gg-config-thing-$PROJECT_NAME-$PROJECT_STAGE.json
      - cdk deploy *-ComponentUploadStack --require-approval never
      - cdk deploy *-ComponentDeploymentStack --require-approval never
      - cdk deploy *-DataPipelineStack --require-approval never
      - echo ==--------CompleteDeploy---------==

artifacts:
  files: '**/*'